apiVersion: v1
kind: Service
metadata:
  labels:
    service: ads
  name: ads
spec:
  ports:
  - name: "8001"
    port: 8001
    targetPort: 8001
  selector:
    service: ads
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: ads
  name: ads
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: ads
    spec:
      containers:
      - env:
        - name: GOOGLE_CLOUD_PROJECT
          value: [PROJECT_ID]
        image: gcr.io/[PROJECT_ID]/hipster-ads
        name: ads
        ports:
        - containerPort: 8001
