apiVersion: v1
kind: Service
metadata:
  labels:
    service: frontend
  name: frontend
  namespace: microservice
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 8080
  selector:
    service: frontend
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: frontend
  name: frontend
  namespace: microservice
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: frontend
    spec:
      containers:
      - env:
        - name: ADS_SERVICE_ENDPOINT
          value: ads:8001
        - name: DB_HOST
          value: [DB_IP]:3306
        - name: DB_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: dbsecret
              key: password
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: dbsecret
              key: username
        - name: RECOMMENDATION_SERVICE_ENDPOINT
          value: recommendation
        - name: RECOMMENDATION_SERVICE_PORT
          value: "50051"
        - name: ZEEBE_SERVICE_ENDPOINT
          value: zeebe:26500
        image: gcr.io/cloud-solutions-images/ecomm-frontend
        imagePullPolicy: Always
        name: frontend
        ports:
        - containerPort: 8080
