apiVersion: v1
kind: Service
metadata:
  labels:
    service: payment
  name: payment
  namespace: microservice
spec:
  ports:
  - name: "9001"
    port: 9001
    targetPort: 8080
  selector:
    service: payment
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: payment
  name: payment
  namespace: microservice
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: payment
    spec:
      containers:
      - env:
        - name: ZEEBE_SERVICE_ENDPOINT
          value: zeebe:26500
        image: gcr.io/cloud-solutions-images/ecomm-payment
        imagePullPolicy: Always
        name: payment
        ports:
        - containerPort: 8080
