apiVersion: v1
kind: Service
metadata:
  labels:
    service: recommendation
  name: recommendation
spec:
  ports:
  - name: "50051"
    port: 50051
    targetPort: 50051
  selector:
    service: recommendation
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: recommendation
  name: recommendation
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: recommendation
    spec:
      containers:
      - env:
        image: gcr.io/[PROJECT_ID]/hipster-recommendation
        name: recommendation
        ports:
        - containerPort: 50051
