apiVersion: v1
kind: Service
metadata:
  labels:
    service: zeebe
  name: zeebe
  namespace: microservice
spec:
  ports:
  - name: "26500"
    port: 26500
    targetPort: 26500
  selector:
    service: zeebe
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: zeebe
  name: zeebe
  namespace: microservice
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: zeebe
    spec:
      containers:
      - env:
        - name: ZEEBE_LOG_LEVEL
          value: debug
        image: camunda/zeebe:0.20.0
        name: zeebe
        ports:
        - containerPort: 26500
